
name: GitHub Actions Demo
on:
  push:
    paths-ignore: ".github/**"
  pull_request:
    branches: main
  schedule: 
    - cron: '15 6 * * 0'
  workflow_dispatch:
jobs: 
  MyJob:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Run some task
        run: | 
          echo ${{ github.event_name }}
          echo ${{ github.event}}
      - name: List files
        shell: pwsh
        run: get-childitem -recurse
